name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
        unzip gradle-7.5-bin.zip
        echo "$PWD/gradle-7.5/bin" >> $GITHUB_PATH

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
